const DATA=window.TSOC_EXERCISE_DATA;const state={category:'ALL',preset:null,search:'',selected:[]};const ORDER=new Map(DATA.exercises.map((e,i)=>[e.id,i]));
const $=s=>document.querySelector(s);const byId=id=>DATA.exercises.find(x=>x.id===id);
function init(){DATA.categories.forEach(c=>{const b=document.createElement('button');b.className='nav';b.textContent=c;b.onclick=()=>setCategory(c);$('#categoryNav').appendChild(b)});DATA.presets.forEach(p=>{const b=document.createElement('button');b.className='preset-btn';b.textContent=p.name;b.title=`${p.exercise_ids.length}種目`;b.onclick=()=>setPreset(p);$('#presetNav').appendChild(b)});$('#search').oninput=e=>{state.search=e.target.value.trim().toLowerCase();renderGrid()};$('#clearBtn').onclick=()=>{state.selected=[];renderAll()};$('#printBtn').onclick=printMenu;renderAll()}
function setCategory(c){state.category=c;state.preset=null;document.querySelectorAll('.preset-btn').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',(c==='ALL'&&b.dataset.cat==='ALL')||b.textContent===c));renderGrid()}
function selectedId(id){return state.selected.find(x=>x.id===id)}
function toggle(id){const i=state.selected.findIndex(x=>x.id===id);if(i>=0)state.selected.splice(i,1);else{if(state.selected.length>=DATA.max_selection){notice('選択できる運動は最大8種目です。');return}state.selected.push({id,reps:'',unit:'回',sets:''});state.selected.sort((a,b)=>ORDER.get(a.id)-ORDER.get(b.id))}renderAll()}
function notice(t){const n=$('#notice');n.textContent=t;n.classList.remove('hidden');setTimeout(()=>n.classList.add('hidden'),2500)}
function setPreset(p){state.preset=p;state.category='ALL';document.querySelectorAll('.nav').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.preset-btn').forEach(b=>b.classList.toggle('active',b.textContent===p.name));renderGrid()}
function filtered(){const pset=state.preset?new Set(state.preset.exercise_ids):null;return DATA.exercises.filter(e=>(pset?pset.has(e.id):(state.category==='ALL'||e.category===state.category))&&(!state.search||(`${e.name} ${e.purpose} ${e.description}`).toLowerCase().includes(state.search)))}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function renderGrid(){const g=$('#exerciseGrid');g.innerHTML='';filtered().forEach(e=>{const card=document.createElement('article');card.className='exercise-card'+(selectedId(e.id)?' selected':'');const imgs=e.images.length?`<div class="photo-strip">${e.images.map(src=>`<img loading="lazy" src="${src}" alt="">`).join('')}</div>`:`<div class="no-photo">画像なし</div>`;card.innerHTML=`${imgs}<div class="card-body"><div class="tag">${esc(e.category)}</div><h3 class="card-title">${esc(e.name)}</h3><p class="purpose">${esc(e.purpose)}</p><div class="description">${esc(e.description)}</div></div>`;card.onclick=()=>toggle(e.id);g.appendChild(card)})}
function renderSelection(){const box=$('#selectionList');box.innerHTML='';state.selected.forEach((s,idx)=>{const e=byId(s.id);const d=document.createElement('div');d.className='selection-item';d.innerHTML=`<div class="sel-row"><span>${idx+1}.</span><strong>${esc(e.name)}</strong><button class="remove" aria-label="削除">×</button></div><div class="dose"><input class="reps" inputmode="numeric" placeholder="回数/時間" value="${esc(s.reps)}"><select class="unit"><option ${s.unit==='回'?'selected':''}>回</option><option ${s.unit==='秒'?'selected':''}>秒</option></select><input class="sets" inputmode="numeric" placeholder="セット" value="${esc(s.sets)}"></div>`;d.querySelector('.remove').onclick=()=>{state.selected.splice(idx,1);renderAll()};d.querySelector('.reps').oninput=x=>s.reps=x.target.value;d.querySelector('.unit').onchange=x=>s.unit=x.target.value;d.querySelector('.sets').oninput=x=>s.sets=x.target.value;box.appendChild(d)});$('#count').textContent=state.selected.length}
function renderAll(){renderGrid();renderSelection()}
function doseText(s){let t='';if(s.reps)t+=`${s.reps}${s.unit}`;if(s.sets)t+=(t?' × ':'')+`${s.sets}セット`;return t}
function printMenu(){if(!state.selected.length){notice('印刷する運動を選択してください。');return}const patient=$('#patientName').value.trim();const pages=[];for(let i=0;i<state.selected.length;i+=4)pages.push(state.selected.slice(i,i+4));$('#printView').innerHTML=pages.map((page,pi)=>`<section class="print-page"><div class="print-head"><div><h1>自主トレーニング指導メニュー</h1><div>TSOC Exercise</div></div><div class="print-patient">患者名：${esc(patient)}</div></div><div class="print-exercises">${page.map((s,j)=>{const e=byId(s.id);return `<article class="print-ex"><div class="print-images">${e.images.map(src=>`<img src="${src}" alt="">`).join('')}</div><div><h3>${pi*4+j+1}. ${esc(e.name)}</h3><p><strong>${esc(e.purpose)}</strong></p><p>${esc(e.description)}</p><div class="print-dose">${esc(doseText(s))}</div></div></article>`}).join('')}</div><div class="print-footer">TSOC Exercise Web v${DATA.app_version} / Page ${pi+1}</div></section>`).join('');window.print()}
init();
